# Generated by Django 6.1 on 2026-09-29 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PREPARACION', 'En Preparación'), ('LISTO', 'Listo para Entrega'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Instrucciones especiales para cocina/barra', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido / Comanda',
                'verbose_name_plural': 'Pedidos / Comandas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(blank=True, help_text='Ej: Restaurante, Cafetería, Kiosco', max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Punto de Venta',
                'verbose_name_plural': 'Puntos de Venta',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado / Pendiente Descuento'), ('DESCONTADO', 'Descontado por Planilla'), ('ANULADO', 'Anulado')], default='REGISTRADO', max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_internos', to=settings.AUTH_USER_MODEL)),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_internos', to='ventas.puntoventa')),
            ],
            options={
                'verbose_name': 'Consumo Interno',
                'verbose_name_plural': 'Consumos Internos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_hora_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornadas_abiertas', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jornadas_cerradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'ordering': ['-fecha_hora_apertura'],
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('CAJERO', 'Cajero'), ('MESERO', 'Mesero')], default='CAJERO', max_length=20)),
                ('rut', models.CharField(blank=True, help_text='Formato: 12.345.678-9', max_length=12, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Empleado',
                'verbose_name_plural': 'Perfiles de Empleados',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='ventas.categoria')),
                ('puntos_venta', models.ManyToManyField(blank=True, related_name='productos_disponibles', to='ventas.puntoventa')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PrecioEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_condicion', models.CharField(help_text='Motivo o convenio', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_especiales', to='ventas.producto')),
            ],
            options={
                'verbose_name': 'Precio Especial',
                'verbose_name_plural': 'Precios Especiales',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('observaciones', models.CharField(blank=True, help_text='Ej: sin sal, sin hielo, término medio', max_length=200, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='ventas.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
            },
        ),
        migrations.CreateModel(
            name='DetalleConsumoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.consumointerno')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_consumo_interno', to='ventas.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Consumo Interno',
                'verbose_name_plural': 'Detalles de Consumos Internos',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Ej: Mesa 1, Terraza 3', max_length=20)),
                ('capacidad', models.PositiveIntegerField(default=4)),
                ('estado', models.CharField(choices=[('HABILITADA', 'Habilitada / Libre'), ('OCUPADA', 'Ocupada'), ('RESERVADA', 'Reservada'), ('INACTIVA', 'Inactiva / Mantenimiento')], default='HABILITADA', max_length=20)),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mesas', to='ventas.puntoventa')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'unique_together': {('identificador', 'punto_venta')},
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('productos', models.ManyToManyField(blank=True, related_name='menus', to='ventas.producto')),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='ventas.puntoventa')),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Caja 1, Terminal Mostrador', max_length=50)),
                ('monto_apertura', models.DecimalField(decimal_places=2, default=0, help_text='Fondo inicial de sencillo', max_digits=10)),
                ('monto_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_hora_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='ventas.jornada')),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='ventas.puntoventa')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-fecha_hora_apertura'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: COM-0085, TIK-C-0102', max_length=30, unique=True)),
                ('tipo_destino', models.CharField(choices=[('COCINA', 'Cocina Caliente'), ('BARRA', 'Barra / Cafetería'), ('COMPROBANTE', 'Comprobante de Cliente')], default='COCINA', max_length=20)),
                ('estado', models.CharField(choices=[('EMITIDO', 'Emitido'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado')], default='EMITIDO', max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('contenido_impresion', models.TextField(blank=True, help_text='Texto listo para impresora térmica futura', null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ventas.pedido')),
            ],
            options={
                'verbose_name': 'Ticket de Producción',
                'verbose_name_plural': 'Tickets de Producción',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_entrega', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='ventas.pedido')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='ventas.ticket')),
            ],
            options={
                'verbose_name': 'Entrega de Pedido',
                'verbose_name_plural': 'Entregas de Pedidos',
                'ordering': ['-fecha_hora_entrega'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('VENTA_RAPIDA', 'Venta Rápida / Mostrador'), ('MESA', 'Consumo en Mesa')], default='VENTA_RAPIDA', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DEBITO', 'Tarjeta Débito'), ('CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('PAGADA', 'Pagada / Completada'), ('ANULADA', 'Anulada')], default='PAGADA', max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='ventas.caja')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='ventas.mesa')),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='ventas.puntoventa')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='ventas.venta'),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='ventas.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
    ]
