# Generated by Django 6.1 on 2026-09-29 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilempleado',
            name='punto_venta_actual',
            field=models.ForeignKey(blank=True, help_text='Punto de venta o local actual asignado (solo uno por trabajador)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_asignados', to='ventas.puntoventa'),
        ),
        migrations.CreateModel(
            name='AlertaTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, default='Reasignación operativa de personal', max_length=255, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_autorizados', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_traslado', to=settings.AUTH_USER_MODEL)),
                ('punto_venta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados_entrantes', to='ventas.puntoventa')),
                ('punto_venta_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_salientes', to='ventas.puntoventa')),
            ],
            options={
                'verbose_name': 'Alerta de Traslado',
                'verbose_name_plural': 'Alertas de Traslado',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
