# Generated by Django 6.1 on 2026-09-30 01:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_perfilempleado_punto_venta_actual_alertatraslado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(fields=('jornada', 'cajero'), name='unique_caja_por_cajero_jornada'),
        ),
    ]
