# Generated by Django 6.1 on 2026-10-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_caja_unique_caja_por_cajero_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoventa',
            name='color',
            field=models.CharField(blank=True, default='#c62828', help_text='Color distintivo hex', max_length=20),
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='icono',
            field=models.CharField(blank=True, default='bi-shop', help_text='Ícono Bootstrap', max_length=50),
        ),
    ]
