# Generated by Django 6.1 on 2026-10-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_puntoventa_color_puntoventa_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta / En Consumo'), ('PAGADA', 'Pagada / Completada'), ('ANULADA', 'Anulada')], default='PAGADA', max_length=20),
        ),
    ]
